services:
  - type: web
    name: traductor-lengua-senas
    runtime: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
